# SPDX-License-Identifier: LGPL-3.0-or-later
import json
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
# NOTE: G15d needs the live Berreman4x4 sources only for the optional
# integrity spot-check; gates run against ref/ref_out_cholesteric.json
# (generated by ref/gen_cholesteric_ref.py) so no-network CI stays green.
"""Gate G15d: cholesteric circular Bragg vs live B44 (Phase 10b).

Fixture: no=1.5, ne=1.7, pitch 350 nm, N=5 (d=1750 nm), angle=+-2*pi*N,
48 slices/pitch, air/air, normal incidence. Observable: circular R_RR
stopband peak (position <= 0.5%, height <= 3%, FWHM <= 5%) + twist-swap
(angle -> -angle moves the peak to R_LL at the same position).
Sampling: B44 midpoint-evaluation == our grid="midpoint" (verified
5.6e-17 on tensor samples) — discretization drops out; residual is
solver-vs-solver (slice propagator Pade-2 vs exact + Delta form/basis).
"""
import numpy as np

from navette import berreman as bl

REF = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "ref", "ref_out_cholesteric.json")
with open(REF) as fh:
    ref = json.load(fh)
WL = np.array(ref["meta"]["wl_nm"])
assert ref["meta"]["div"] == 240 and ref["meta"]["d_nm"] == 1750.0

try:
    sys.path.insert(0, os.environ.get("B44_DIR", "."))
    from Berreman4x4 import Berreman4x4 as B44
    HAVE_B44 = True
except ImportError:
    HAVE_B44 = False
print("live B44 available:", HAVE_B44)


def metrics(wl, curve):
    """Peak (position, height, FWHM); half-max crossings found by scanning
    outward from the peak (robust to side-lobes), linear interp."""
    i = int(np.argmax(curve))
    pos, height = float(wl[i]), float(curve[i])
    half = height / 2
    jl = i
    while jl > 0 and curve[jl] > half:
        jl -= 1
    denom_l = curve[jl + 1] - curve[jl]
    left = wl[jl] + (wl[jl + 1] - wl[jl]) * (half - curve[jl]) / denom_l
    jr = i
    n = len(curve)
    while jr < n - 1 and curve[jr] > half:
        jr += 1
    denom_r = curve[jr] - curve[jr - 1]
    right = wl[jr - 1] + (wl[jr] - wl[jr - 1]) * (half - curve[jr - 1]) / denom_r
    return pos, height, float(right - left)


def our_scan(sign, npp=48):
    layers = bl.cholesteric_stack(1.5, 1.7, 350.0, 5, n_per_pitch=npp)
    if sign < 0:
        layers = bl.twisted_stack(np.diag([1.7 ** 2, 1.5 ** 2, 1.5 ** 2]),
                                  1750.0, -2 * np.pi * 5, 5 * npp)
    s = bl.BerremanStack(layers, WL, [0.0]).solve()
    assert s["n_failed"] == 0
    jc = np.asarray(s["J_refl_circ"])  # squeezed [n_wl, 2, 2] (n_th == 1)
    return np.abs(jc[:, 0, 0]) ** 2, np.abs(jc[:, 1, 1]) ** 2


# ── integrity spot-check (live B44 vs committed JSON, 5 wavelengths) ─────────
if HAVE_B44:
    F = np.array([[1, 1], [-1j, 1j]])
    BINV = np.linalg.inv(np.array([[1, 1], [1j, -1j]]))
    base = B44.NonDispersiveMaterial(
        epsilon=np.matrix(np.diag([1.7 ** 2, 1.5 ** 2, 1.5 ** 2])))
    tw = B44.TwistedMaterial(base, 1750e-9, 2 * np.pi * 5, 240)
    air = B44.IsotropicHalfSpace(B44.IsotropicNonDispersiveMaterial(n=1.0))
    bst = B44.Structure(
        front=air,
        layers=[B44.InhomogeneousLayer(tw, "midpoint", "Padé", 2)], back=air)
    worst_spot = 0.0
    for w in (WL[0], WL[20], WL[38], WL[60], WL[-1]):
        k0 = 2 * np.pi / (w * 1e-9)
        tri, _ = (np.asarray(m, dtype=complex) for m in bst.getJones(0.0, k0))
        jc = BINV @ tri @ F
        k = int(np.argmin(np.abs(WL - w)))
        worst_spot = max(worst_spot,
                         abs(abs(jc[0, 0]) ** 2 - ref["helicity"]["plus"]["R_RR"][k]))
    print(f"JSON integrity spot-check: {worst_spot:.3e}")
    assert worst_spot < 1e-9, "stale JSON?"
else:
    print("JSON integrity spot-check SKIPPED (no live B44)")

# ── convergence triple (our side) + gates at 48 ──────────────────────────────
triple = {}
for npp in (24, 48, 96):
    r_rr, _ = our_scan(+1, npp)
    triple[npp] = metrics(WL, r_rr)
    print(f"ours npp={npp}: pos={triple[npp][0]:.1f} height={triple[npp][1]:.6f} "
          f"fwhm={triple[npp][2]:.2f}")
assert triple[24][1] < triple[48][1] < triple[96][1], "not monotone"
h48, h96 = triple[48][1], triple[96][1]
print(f"48-vs-96 height convergence: {abs(h48 - h96) / h96:.3e}")
assert abs(h48 - h96) / h96 < 1e-3, "undiscretized?"

pos, height, fwhm = triple[48]
rpos = WL[int(np.argmax(ref["helicity"]["plus"]["R_RR"]))]
rhei = max(ref["helicity"]["plus"]["R_RR"])
_, _, rfwhm = metrics(WL, np.array(ref["helicity"]["plus"]["R_RR"]))
print(f"ours: pos={pos:.1f} height={height:.6f} fwhm={fwhm:.2f}")
print(f"ref : pos={rpos:.1f} height={rhei:.6f} fwhm={rfwhm:.2f}")
dpos = abs(pos - rpos) / rpos
dhei = abs(height - rhei) / rhei
dwid = abs(fwhm - rfwhm) / rfwhm
print(f"G15d: dpos={dpos:.3e} dhei={dhei:.3e} dfwhm={dwid:.3e}")
assert dpos < 0.005, "G15d position failed"
assert dhei < 0.03, "G15d height failed"
assert dwid < 0.05, "G15d FWHM failed"
print("G15d PASS")

# ── twist-swap (both sides) ──────────────────────────────────────────────────
m_rr, m_ll = our_scan(-1)
spos, shei, _ = metrics(WL, m_ll)
print(f"ours -angle: R_LL peak pos={spos:.1f} height={shei:.6f}; "
      f"R_RR suppressed to {m_rr.max():.6f}")
assert abs(spos - pos) / pos < 0.005, "swap position failed"
assert m_rr.max() < 0.05 * shei, "swap suppression failed"
bpos, _, _ = metrics(WL, np.array(ref["helicity"]["minus"]["R_LL"]))
print(f"ref -angle R_LL peak pos={bpos:.1f} (must match +angle R_RR {rpos:.1f})")
assert abs(bpos - rpos) / rpos < 0.005, "reference swap inconsistent"
print("swap PASS")
